name: CI for different Linux distributions

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download cmake
      run: |
        wget https://cmake.org/files/v3.18/cmake-3.18.2-Linux-x86_64.tar.gz
        tar xf cmake-3.18.2-Linux-x86_64.tar.gz
    - name: build
      run: |
        mkdir build && cd build
        ../cmake-3.18.2-Linux-x86_64/bin/cmake ..
        make
    - name: unit tests
      run: |
        cd build
        ../cmake-3.18.2-Linux-x86_64/bin/ctest -j2 -V -E inttest.*
    - name: regression tests
      run: |
        cd build
        ../cmake-3.18.2-Linux-x86_64/bin/ctest --stop-on-failure -j2 -V -R inttest.*

  test-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_image: ["fedora:latest", "debian:10", "archlinux/base", "ubuntu:bionic", "centos:7", "opensuse/tumbleweed", "alpine:latest"]
        include:
        - container_image: "fedora:latest"
          cmake: "cmake"
          ctest: "../cmake-3.18.2-Linux-x86_64/bin/ctest"
        - container_image: "debian:10"
          cmake: "cmake"
          ctest: "../cmake-3.18.2-Linux-x86_64/bin/ctest"
        - container_image: "archlinux/base"
          cmake: "cmake"
          ctest: "ctest"
        - container_image: "ubuntu:bionic"
          cmake: "../cmake-3.18.2-Linux-x86_64/bin/cmake"
          ctest: "../cmake-3.18.2-Linux-x86_64/bin/ctest"
        - container_image: "centos:7"
          cmake: "cmake"
          ctest: "../cmake-3.18.2-Linux-x86_64/bin/ctest"
        - container_image: "opensuse/tumbleweed"
          cmake: "cmake"
          ctest: "ctest"
        - container_image: "alpine:latest"
          cmake: "cmake"
          ctest: "ctest"
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_dependencies.sh
    - name: download cmake
      run: |
        wget https://cmake.org/files/v3.18/cmake-3.18.2-Linux-x86_64.tar.gz
        tar xf cmake-3.18.2-Linux-x86_64.tar.gz
        export PATH=$(pwd)/cmake-3.18.2-Linux-x86_64/bin:${PATH}
    - name: build
      run: |
        mkdir build && cd build
        ${{ matrix.cmake }} ..
        make
    - name: unit tests
      run: |
        cd build
        ${{ matrix.ctest }} -j2 -V -E inttest.*
    - name: regression tests
      run: |
        cd build
        ${{ matrix.ctest }} --stop-on-failure -j2 -V -R inttest.*
