name: CI for Windows

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  windows-build-and-test:
    name: Windows build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          md build
          cd build
          cmake ..
          cmake --build .
      - name: unit tests
        run: |
          cd build
          ctest -j2 -V -E inttest.*
      - name: regression tests
        run: |
          cd build
          ctest -j2 -V -C Debug -R inttest.*
